### ISSUE TITLE
Model Body include statements should have .view.lkml suffix

### ISSUE THREAD

**Issue by yomiBazuaye** [Cimpress-MCP/j2v#13]
Here's an example input statement  <MODEL BODY>:

`<MODEL BODY>
include: "manufacturing_issues"
 `

Looker does not appear to like this syntax. Correct syntax appears to be :

`<MODEL BODY>
include: "manufacturing_issues.view.lkml"
 `
![image](https://user-images.githubusercontent.com/6269982/63162982-504ba080-c024-11e9-937b-4e1dad08c873.png)

![image](https://user-images.githubusercontent.com/6269982/63162996-65c0ca80-c024-11e9-9705-f15b171a0af9.png)

**Comment by mzas** [comment]
That's fixed in https://github.com/Cimpress-MCP/j2v/pull/14
